language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
script:
- python bin/archive.py
after_success:
- openssl aes-256-cbc -K $encrypted_c57ccc1bf147_key -iv $encrypted_c57ccc1bf147_iv -in .travis/archiver_rsa.enc -out .travis/archiver_rsa -d
- bin/push.sh
